### ISSUE TITLE
Compress the pictures to load the page faster.

### ISSUE THREAD

**Issue by maciej-jasiewicz** [mikaelmonteirodev/BandaJoio-Website#1]
My idea of what can be improved is to compress the pictures to load the page faster for users with slow internet connection.

Greetings

**Comment by mikaelmonteirodev** [comment]
Hi @0x0undefined ! Great comment. Thank you for your collaboration. So, do you have any site suggestions for compressing the images? 

[> compress the pictures to load the page faster for users with slow internet connection.](https://github.com/mikaelmonteirodev/BandaJoio-Website/commit/fd5ff318694bc14d21c2552a847848cbccd92717#r87963687)

**Comment by maciej-jasiewicz** [comment]
My suggestion is to use: https://github.com/apps/imgbot

Best regards

**Comment by mikaelmonteirodev** [comment]
OK. I installed "Imgbot" on my github, but it didn't start compressing the images automatically as it says in the instructions. So I compressed the images in another way. I hope it got better.

Link to PR: https://github.com/mikaelmonteirodev/BandaJoio-Website/pull/2#issue-1424896277

**Comment by mikaelmonteirodev** [comment]
Hello [0x0undefined](https://github.com/0x0undefined). I come again to thank you for the suggestion of imgbot. It ran on all my repositories. Thanks! 

In this repo he created this PR #3

**Comment by maciej-jasiewicz** [comment]
My suggestion is to change the image format to ".webp", which is more optimized and lightweight 

Best regards

**Comment by maciej-jasiewicz** [comment]
@mikaelmonteirodev please respond :)

**Comment by mikaelmonteirodev** [comment]
Hello @0x0undefined  I'm sorry. I was waiting for guidance from my teacher. But if you can direct me to the best way to make this change I would be grateful.

**Comment by maciej-jasiewicz** [comment]
> Hello @0x0undefined I'm sorry. I was waiting for guidance from my teacher. But if you can direct me to the best way to make this change I would be grateful.

I created pull request #4 so you can merge my changes.

Have a nice day 👍

**Comment by mikaelmonteirodev** [comment]
Great! Thank you very much for your time. I wanted to know your opinion on a situation:

 I saw in the imgbot <a href="https://github.com/imgbot/Imgbot/issues/1049#issuecomment-1123727328">repository</a> on Github that they still don't have support for compressing the webp format. So, do you think it's better to keep this change to the webp you kindly made or wait for an update from imgbot that can compress this format?

Thank you once again! 👍

**Comment by mikaelmonteirodev** [comment]
I believe the issue problem is solved, right? So, what do you think about us discussing the webp improvement in PR #4?

Thank you again! 👍
